name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: ['1.16']

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: get yarn
        run: |
          npm install --global yarn

      - name: get protoc
        run: |
          make setup-build-env

      - name: build native
        run: |
          make

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
