name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        go: ['1.16']
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - if: matrix.os == 'windows-latest'
        name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: get yarn
        run: |
          npm install --global yarn

      - if: matrix.os == 'macos-latest'
        name: get protoc
        run: |
          make setup-build-env

      - if: matrix.os == 'ubuntu-latest'
        name: get protoc
        run: |
          sudo make setup-build-env

      - name: build native
        run: |
          make

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
